apiVersion: v1
kind: Service
metadata:
  name: rudra-service
  labels:
    app: {{ .Values.app.label }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.label }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000