apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ros2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - ros2.local
      secretName: tls-secret
  rules:
    - host: ros2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ros2-service
                port:
                  number: 80