apiVersion: v1
kind: Service
metadata:
  name: rudra-service
  labels:
    app: ros2  #✅ ADD THIS
spec:
  type: LoadBalancer
  selector:
    app: ros2 #✅ SAME label
  ports:
    - name: http    # ✅ IMPORTANT
      port: 80
      targetPort: 8000